# Generated by Django 3.1.3 on 2021-04-28 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0002_auto_20210423_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowcollectionassignment',
            name='expiration',
            field=models.DateField(default=datetime.date(2021, 5, 29)),
        ),
    ]
