# Generated by Django 3.1.8 on 2021-06-02 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0002_auto_20210518_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstepuserinput',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique UUID for the database record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowstepuserinput',
            name='required',
            field=models.BooleanField(help_text='True if a value is required for this input in the response JSON'),
        ),
        migrations.AlterField(
            model_name='workflowstepuserinput',
            name='ui_identifier',
            field=models.CharField(help_text='A simple string which is used to indicate to a user interface where to display this object within a template.', max_length=200),
        ),
        migrations.AlterField(
            model_name='workflowstepuserinput',
            name='workflow_step',
            field=models.ForeignKey(help_text='The WorkflowStep object that will own this object.', on_delete=django.db.models.deletion.CASCADE, to='django_workflow_system.workflowstep'),
        ),
        migrations.AlterField(
            model_name='workflowstepuserinputtype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique UUID for the database record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowstepuserinputtype',
            name='name',
            field=models.CharField(help_text='The name of the question type.', max_length=150),
        ),
        migrations.AlterField(
            model_name='workflowstepuserinputtype',
            name='placeholder_specification',
            field=models.JSONField(help_text='An example of properly formatted json that follows the json_schema.'),
        ),
    ]
