# Generated by Django 3.1.8 on 2021-06-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0003_auto_20210602_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowstepuserinputtype',
            old_name='placeholder_specification',
            new_name='example_specification',
        ),
    ]
