# Generated by Django 3.1.8 on 2021-04-29 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0003_auto_20210428_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowcollectionassignment',
            options={'ordering': ['workflow_collection', 'start'], 'verbose_name_plural': 'Workflow Collection Assignments'},
        ),
        migrations.RemoveField(
            model_name='workflowcollectionassignment',
            name='assigned_on',
        ),
        migrations.RemoveField(
            model_name='workflowcollectionassignment',
            name='expiration',
        ),
        migrations.AddField(
            model_name='workflowcollectionassignment',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowcollectionassignment',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
