# Generated by Django 3.1.8 on 2021-05-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0003_auto_20210519_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcollection',
            name='metadata',
            field=models.ManyToManyField(blank=True, help_text='A list of metadata that this collection is associated with.', to='django_workflow_system.WorkflowMetadata'),
        ),
    ]
