# Generated by Django 3.1.8 on 2021-07-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0003_auto_20210617_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowmetadata',
            options={'verbose_name_plural': 'Workflow Metadata'},
        ),
    ]
