# Generated by Django 3.1.8 on 2021-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0004_auto_20210429_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowsteptext',
            name='content',
        ),
        migrations.RemoveField(
            model_name='workflowsteptext',
            name='storage_value',
        ),
        migrations.AddField(
            model_name='workflowsteptext',
            name='text',
            field=models.CharField(default='WorkflowStepText Placeholder', max_length=1000),
        ),
    ]
