# Generated by Django 3.1.8 on 2021-05-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0004_workflowcollection_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='metadata',
            field=models.ManyToManyField(blank=True, help_text='A list of metadata that this workflow is associated with.', to='django_workflow_system.WorkflowMetadata'),
        ),
    ]
