# Generated by Django 3.1.8 on 2021-05-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0005_auto_20210510_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowsteptext',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
