# Generated by Django 3.1.8 on 2021-05-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0005_workflow_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowcollectiontagoption',
            name='type',
        ),
        migrations.RemoveField(
            model_name='workflowcollection',
            name='tags',
        ),
        migrations.DeleteModel(
            name='WorkflowCollectionTagAssignment',
        ),
        migrations.DeleteModel(
            name='WorkflowCollectionTagOption',
        ),
        migrations.DeleteModel(
            name='WorkflowCollectionTagType',
        ),
    ]
