# Generated by Django 3.1.8 on 2021-05-10 11:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0006_auto_20210510_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepExternalLink',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ui_identifier', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=500)),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_workflow_system.workflowstep')),
            ],
            options={
                'verbose_name_plural': 'Workflow Step External Links',
                'db_table': 'workflow_system_step_external_link',
                'unique_together': {('workflow_step', 'ui_identifier')},
            },
        ),
    ]
