# Generated by Django 3.1.8 on 2021-05-10 12:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0007_workflowstepexternallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStepUserInput',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ui_identifier', models.CharField(max_length=200)),
                ('required', models.BooleanField()),
                ('response_schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_workflow_system.jsonschema')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_workflow_system.workflowstep')),
            ],
            options={
                'verbose_name_plural': 'Workflow Step User Inputs',
                'db_table': 'workflow_system_step_user_input',
                'unique_together': {('workflow_step', 'ui_identifier')},
            },
        ),
        migrations.DeleteModel(
            name='WorkflowStepInput',
        ),
    ]
