# Generated by Django 3.1.8 on 2021-07-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0007_additional_user_input_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowcollectionmember',
            options={'ordering': ['order'], 'verbose_name_plural': 'Workflow Collection Members'},
        ),
        migrations.AlterField(
            model_name='workflowstepuserinputtype',
            name='name',
            field=models.CharField(help_text='The name of the question type.', max_length=150, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstepuserinputtype',
            unique_together=set(),
        ),
    ]
