# Generated by Django 3.2.9 on 2021-11-04 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_workflow_system', '0009_update_user_input_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowcollectionengagement',
            name='finished',
            field=models.DateTimeField(blank=True, help_text='When the user finished the engagement.', null=True),
        ),
        migrations.AlterField(
            model_name='workflowcollectionengagement',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the user started the engagment.'),
        ),
        migrations.AlterField(
            model_name='workflowcollectionengagement',
            name='user',
            field=models.ForeignKey(help_text='The user to whom the engagement belongs.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowcollectionengagement',
            name='workflow_collection',
            field=models.ForeignKey(help_text='The collection which the engagement records data for.', on_delete=django.db.models.deletion.PROTECT, to='django_workflow_system.workflowcollection'),
        ),
    ]
