# Generated by Django 3.1.8 on 2021-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0009_auto_20210510_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowstepuserinputtype',
            old_name='placeholder_spec',
            new_name='placeholder_specification',
        ),
        migrations.AlterField(
            model_name='workflowstepuserinputtype',
            name='json_schema',
            field=models.JSONField(help_text='Used to specify input, label, options, and correct answers.', verbose_name='JSON Schema'),
        ),
    ]
