# Generated by Django 3.1.8 on 2021-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_system', '0010_auto_20210511_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepuserinputtype',
            name='response_schema',
            field=models.JSONField(blank=True, help_text='The schema that a user response must adhere to.', null=True),
        ),
    ]
